### ISSUE TITLE
Problem with file download

### ISSUE THREAD

**Issue by pbourgos** [PHANTOM-Platform/Repository#1]
I have uploaded an xml (cpn.xml) file with repo_put.java and tried to download it afterwards with the repo_get_file.java. It didnt seem to find the file and failed to download it.
Associated json file:
{
  "project":"phantom_tools_on_Test",
  "source":"user",
  "type":"Usercase",
  "name":"Test",
  "content":"xml_file"
}

**Comment by jmmontanana** [comment]
I look into it now !!!

2018-04-20 18:03 GMT+02:00 pbourgos <notifications@github.com>:

**Comment by jmmontanana** [comment]
The file was successfully uploaded to the server

Now I look what happens on the repo_get_file.java

You can see the content I copy here:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<application name="Example_Application"
value="general-purpose">


<requirements name="global_requirements" set-by="USER"
target="Example_Application">

<non-functional max-value="700" measurement-unit="ns" name="global_WCET"
type="execution-time"/> 
<non-functional max-value="350" measurement-unit="milliwatt"
name="global_WCPC" type="power-consumption"/> 

<monitoring name="global_monitor" type="execution-time"/> 
</requirements>


<component name="A" type="asynchronous">

 

<MBT-estimated-computation-time measurement-unit="ns" value="250"/>  

<MF-monitored-computation-time measurement-unit="ns" value="150"/>
<MF-monitored-power-consumption measurement-unit="milliwatt" value="50"/>


<requirements name="component_A_requirements" set-by="USER" target="A">

<non-functional max-value="400" measurement-unit="ns" name="CA_WCET"
type="execution-time"/> 

<monitoring name="CA_monitor" type="execution-time"/> 
</requirements>

<header file="CA.h" lang="c"/>
<source file="CA.c" lang="c"/>

<port name="out" peer-name="in" peer-object="BF1" type="out"/>
<loop FPGA-compatible="false" GPU-compatible="false" id="0"
loop-iterations="4" parallelizable="false"/>
<loop FPGA-compatible="false" GPU-compatible="false" id="0"
loop-iterations="4" parallelizable="true"/>
</component>

<component name="B" type="asynchronous">

 

<MBT-estimated-computation-time measurement-unit="ns" value="300"/>  

<MF-monitored-computation-time measurement-unit="ns" value="150"/>
<MF-monitored-power-consumption measurement-unit="milliwatt" value="50"/>

<header file="CB.h" lang="c"/>
<source file="CB.c" lang="c"/>

<port name="in" peer-name="out" peer-object="BF1" type="in"/>

<loop FPGA-compatible="false" GPU-compatible="false" id="0"
loop-iterations="4" parallelizable="true"/>
<loop FPGA-compatible="false" GPU-compatible="true" id="1"
loop-iterations="8" parallelizable="true"/>

</component>


<comm-object item-size="8" name="BF1" object-class="FIFO" size="128"
type="Queue">

<requirements name="BF2_requirements" set-by="USER" target="BF2">

<data-integrity measurement-unit="data" value="true"/> 
</requirements>

<PT-access-number set-by="PT" value="64"/> 

<source name="A" port-name="in"/>
<target name="B" port-name="out"/>
</comm-object>

</application>


2018-04-20 18:04 GMT+02:00 Jose Miguel <jmmontanana@gmail.com>:

**Comment by pbourgos** [comment]
Yes, upload seems ok

**Comment by jmmontanana** [comment]
found error in the file repo_get_file.java

fixed on the attached copy, I will upload now on the GitHub

I achieve to receive the file from the repository running as:

java -classpath org.json.jar:apache-httpcomponents-httpcore.jar:.
demo_phantom/repo_get_file
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb250YW5hQGFiYy5jb20iLCJpYXQiOjE1MjIwNjg2MTEsImV4cCI6MTUyNDY2MDYxMX0.IjXYKMQFfqU-J8O-tlicyCEr_S9q3kvJ5tusPJCpM2s"
"141.58.0.8" "2777" "phantom_tools_on_Test" "user" "otherpath" "cpn.xml";


Thank you for your request



2018-04-20 18:12 GMT+02:00 pbourgos <notifications@github.com>:

**Comment by jmmontanana** [comment]
Detected the error in the file repo_get_file.java and fixed.

**Comment by pbourgos** [comment]
The problem is fixed for cpn.xml, but I cannot download the new.h file now. See sequence below.
-------
pbourgos@pbourgos-VirtualBox:~/Projects/PHANTOM/Repository/api_java$ sudo bash demo_java_PB.sh 
REQUESTING A NEW TOKEN ....
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJib3VyZ29zQHdpbmdzLWljdC1zb2x1dGlvbnMuZXUiLCJpYXQiOjE1MjQ0NzMyNzIsImV4cCI6MTUyNzA2NTI3Mn0.6tCPBBKYUt7D9OfeoVeKxtXhfRCSFOxdhECkJxEi1kY

VERIFIYING THE TOKEN ...
The token is valid !!!.

UPLOADING A FILE ... project=demo_hpc source=user path=mypath file=new.h (project and source defined in the json file)
Project and Source are defined in the json file !!!
200
DOWNLOADING A FILE... project=demo_hpc source=user path=mypath file=new.h

GET request to Repository using the url: http://141.58.0.8:2777/download?project=demo_hpc&source=user&filepath=otherpath&filename=new.h
