### ISSUE TITLE
Project directory download 

### ISSUE THREAD

**Issue by gtzanet** [PHANTOM-Platform/Repository#3]
A method 'get_project()' for downloading a whole project (in zip format or similar) would be really useful, if not necessary, for tools like the PT or the DM. Downloading all the files one by one would be impossible since there is no analytical review of the contents of the project, and it would also be inefficient.

**Comment by jmmontanana** [comment]
Dear Diannis,

It is on the list of things to do.

Thank you for asking for it

Best regards
José Miguel

2018-04-23 18:03 GMT+02:00 Giannis Tzanettis <notifications@github.com>:

**Comment by gtzanet** [comment]
Dear Jose,

I have implemented a java class which **downloads** the project and **unzips** it into a local version of the Repository. Should I upload it on the github?

Giannis

**Comment by jmmontanana** [comment]
Good !!!

thank you

where you put in the svn?

2018-05-25 11:16 GMT+02:00 Giannis Tzanettis <notifications@github.com>:

**Comment by gtzanet** [comment]
I just uploaded it, it's in the "Repository" folder.

**Comment by jmmontanana** [comment]
added functionalities, already tested.

 ============== IN THE VESION WITHOUT INTEGRATION WITH THE SECURITY SERVER ====

FIRST EXAMPLE: DOWNLOADING ALL FILES INCLUDED IN A PARTICULAR PATH IN THE PROJECT:
	curl -s -H "Content-Type: multipart/form-data" -XGET http://${server}:${repository_port}/downloadzip?project=phantom_tools_on_HPC\&source=user\&filepath=mypath --output demo1.zip;

SECOND EXAMPLE: DOWNLOADING ALL FILES IN A PROJECT
	curl -s  -H "Content-Type: multipart/form-data" -XGET http://${server}:${repository_port}/downloadzip?project=phantom_tools_on_HPC --output demo2.zip;

================= IN THE VERSION INTEGRATED WITH THE SECURITY SERVER ====

FIRST EXAMPLE: DOWNLOADING ALL FILES INCLUDED IN A PARTICULAR PATH IN THE PROJECT:
	curl -s -H "Authorization: OAuth ${mytoken}" -H "Content-Type: multipart/form-data" -XGET http://${server}:${repository_port}/downloadzip?project=phantom_tools_on_HPC\&source=user\&filepath=mypath --output demo1.zip;

SECOND EXAMPLE: DOWNLOADING ALL FILES IN A PROJECT
	curl -s -H "Authorization: OAuth ${mytoken}" -H "Content-Type: multipart/form-data" -XGET http://${server}:${repository_port}/downloadzip?project=phantom_tools_on_HPC --output demo2.zip;
